version: '3'
services:
  gradle:
    build: .
    working_dir: $APP_PATH
    volumes:
      - ./config:$APP_PATH/config
      - ./src:$APP_PATH/src
      - ./build.gradle:$APP_PATH/build.gradle
      - ./settings.gradle:$APP_PATH/settings.gradle
      - gradle_cache:/home/gradle/.gradle
    command: gradle --help
volumes:
  gradle_cache: